apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox
  name: busybox
spec:
  replicas: 2
  template:
    spec:
      containers:
      - image: busybox
        name: busybox-cluster01
